### ISSUE TITLE
Check for unique titles/shortcodes

### ISSUE THREAD

**Issue by davdebcom** [davdebcom/post-snippets#81]
In the current versions (2.5 and 3.0) there does not seem to be a check for unique names. So, if a snippet is used as a shortcode, PS will display the last one. This is off course not good, so we need to implement a check to make sure a snippet title is unique. It might be best to implement this with/after the migration to a custom table. 

@sultann Any thoughts on this?

![screen shot 2018-01-19 at 12 51 22](https://user-images.githubusercontent.com/524491/35149724-8769c794-fd17-11e7-95ff-52663a571723.png)
![screen shot 2018-01-19 at 12 51 30](https://user-images.githubusercontent.com/524491/35149725-8784c4fe-fd17-11e7-9483-a0896c4cad6b.png)
![screen shot 2018-01-19 at 12 51 37](https://user-images.githubusercontent.com/524491/35149726-879d49e8-fd17-11e7-98b9-abe3f724b9b3.png)

**Comment by sultann** [comment]
Yes, that on my mind too. Will implement on the refactoring release.


On 19 January, 2018 at 5:53:29 PM, David de Boer (notifications@github.com)
wrote:

In the current versions (2.5 and 3.0) there does not seem to be a check for
unique names. So, if a snippet is used as a shortcode, PS will display the
last one. This is off course not good, so we need to implement a check to
make sure a snippet title is unique. It might be best to implement this
with/after the migration to a custom table.

@sultann <https://github.com/sultann> Any thoughts on this?

[image: screen shot 2018-01-19 at 12 51 22]
<https://user-images.githubusercontent.com/524491/35149724-8769c794-fd17-11e7-95ff-52663a571723.png>
[image: screen shot 2018-01-19 at 12 51 30]
<https://user-images.githubusercontent.com/524491/35149725-8784c4fe-fd17-11e7-9483-a0896c4cad6b.png>
[image: screen shot 2018-01-19 at 12 51 37]
<https://user-images.githubusercontent.com/524491/35149726-879d49e8-fd17-11e7-98b9-abe3f724b9b3.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/davdebcom/post-snippets/issues/81>, or mute the thread

**Comment by davdebcom** [comment]
Please keep this open till we implemented it.
